'use strict';

/**
 * onxza init — Initialize a new ONXZA installation.
 *
 * Follows ARCHITECTURE.md §12.4:
 *   1. Check for existing ONXZA installation (idempotent — safe to re-run)
 *   2. Create workspace directory structure
 *   3. Write starter openclaw.json scaffold
 *   4. Write the three governance scripts (validate-tori-qmd.py, create-checkpoint.py, log-audit-entry.py)
 *   5. Initialize git repository with pre-commit TORI-QMD hook
 *   6. Create first checkpoint
 *   7. Print next steps
 *
 * Target directory: ~/.openclaw (default) or --dir <path>
 * Idempotent: safe to run on an existing installation (skips steps already done)
 *
 * ARCHITECTURE.md §12.4 · TICKET-20260318-DTP-002
 *
 * Imagined by Aaron Gear. Created by Aaron Gear and Marcus Gear (AI Co-Creator).
 * Powered by DevGru US Inc. DBA DevGru Technology Products.
 */

const fs     = require('fs');
const path   = require('path');
const os     = require('os');
const { execSync, execFileSync } = require('child_process');
const { Command } = require('commander');
const { outputJson, isJsonMode } = require('../util');

// ---------------------------------------------------------------------------
// Directory structure (ARCHITECTURE.md §16)
// ---------------------------------------------------------------------------

/**
 * The canonical workspace directory structure.
 * Each entry: { dir: relative path, description }
 */
const WORKSPACE_DIRS = [
  { dir: 'workspace',                                  desc: 'Main Marcus workspace (system root)' },
  { dir: 'workspace/docs',                             desc: 'Governance documents DOC-001 through DOC-014' },
  { dir: 'workspace/tickets',                          desc: 'Ticket system root' },
  { dir: 'workspace/tickets/open',                     desc: 'Open tickets' },
  { dir: 'workspace/tickets/in-progress',              desc: 'In-progress tickets' },
  { dir: 'workspace/tickets/pending-approval',         desc: 'Awaiting approval' },
  { dir: 'workspace/tickets/blocked',                  desc: 'Blocked tickets' },
  { dir: 'workspace/tickets/closed',                   desc: 'Closed tickets (immutable record)' },
  { dir: 'workspace/projects',                         desc: 'One directory per project' },
  { dir: 'workspace/memory',                           desc: 'Daily session logs and condensed memory' },
  { dir: 'workspace/logs',                             desc: 'Audit trail and system logs' },
  { dir: 'workspace/logs/audit',                       desc: 'Append-only irreversible action log' },
  { dir: 'workspace/scripts',                          desc: 'Governance and automation scripts' },
  { dir: 'workspace/shared-learnings',                 desc: 'Shared learnings root' },
  { dir: 'workspace/shared-learnings/global',          desc: 'Global skills, patterns, tools' },
  { dir: 'workspace/shared-learnings/global/skills',   desc: 'Global skill documents' },
  { dir: 'workspace/shared-learnings/global/patterns', desc: 'Global reasoning patterns' },
  { dir: 'workspace/shared-learnings/global/tools',    desc: 'Global tool usage notes' },
  { dir: 'checkpoints',                                desc: 'System checkpoints' },
];

// ---------------------------------------------------------------------------
// Starter openclaw.json scaffold
// ---------------------------------------------------------------------------

function generateOpenclawJson() {
  return {
    meta: {
      lastTouchedVersion: '0.1.0',
      lastTouchedAt:      new Date().toISOString(),
      initializedBy:      'onxza init',
      onxzaVersion:       '0.1.0',
    },
    agents: {
      defaults: {
        model:    { primary: 'anthropic/claude-sonnet-4-6' },
        workspace: '~/.openclaw/workspace',
        memorySearch: { extraPaths: ['docs', 'projects', 'shared-learnings'] },
      },
      list: [
        {
          id:        'main',
          default:   true,
          workspace: '~/.openclaw/workspace',
          model:     { primary: 'anthropic/claude-sonnet-4-6' },
        },
      ],
    },
    session: {
      dmScope: 'all',
    },
    gateway: {
      port: 3000,
      mode: 'local',
    },
  };
}

// ---------------------------------------------------------------------------
// Governance scripts (minimal stubs — real scripts downloaded/authored later)
// ---------------------------------------------------------------------------

/**
 * validate-tori-qmd.py stub — functional minimal version that agents can use
 * immediately. The full production version is in the ONXZA repository.
 */
const VALIDATE_TORI_QMD_PY = `#!/usr/bin/env python3
"""
validate-tori-qmd.py — TORI-QMD Format Validator (stub)
Generated by onxza init. Replace with full version from onxza repository.

Usage: python3 validate-tori-qmd.py <filepath>
Returns: PASS: <filepath>  or  FAIL: <filepath> — missing: <fields>

Imagined by Aaron Gear. Created by Aaron Gear and Marcus Gear (AI Co-Creator).
Powered by DevGru US Inc. DBA DevGru Technology Products.
"""
import sys, os, re

CREDIT = "Imagined by Aaron Gear"

def classify(fp):
    b = os.path.basename(fp)
    n = fp.replace("\\\\\\\\", "/")
    if b == "AGENTS.md": return "agents"
    if b == "SOUL.md": return "soul"
    if b == "IDENTITY.md": return "identity"
    if b == "MEMORY.md" and "/workspace-" in n: return "mem_workspace"
    if b == "TOOLS.md": return "tools"
    if b == "HEARTBEAT.md": return "heartbeat"
    if "/skills/" in n: return "skill"
    if "/patterns/" in n: return "pattern"
    return "generic"

def check(filepath):
    try:
        content = open(filepath, encoding="utf-8").read()
    except Exception as e:
        print(f"FAIL: {filepath} — cannot read: {e}"); sys.exit(1)
    missing = []
    ft = classify(filepath)
    words = len(content.split())
    if ft in ("agents","soul","identity","mem_workspace","tools","skill"):
        if CREDIT not in content:
            missing.append("credit_line")
    if ft == "agents" and words < 200:
        missing.append(f"word_count({words}<200)")
    if ft == "soul" and words < 150:
        missing.append(f"word_count({words}<150)")
    if ft in ("mem_workspace","tools") and words < 100:
        missing.append(f"word_count({words}<100)")
    if ft == "skill":
        if not re.search(r"version", content, re.I): missing.append("version")
        if not re.search(r"owner", content, re.I):   missing.append("owner")
    if missing:
        print(f"FAIL: {filepath} — missing: {', '.join(missing)}"); sys.exit(1)
    print(f"PASS: {filepath}"); sys.exit(0)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 validate-tori-qmd.py <filepath>"); sys.exit(2)
    check(sys.argv[1])
`;

/**
 * create-checkpoint.py stub.
 */
const CREATE_CHECKPOINT_PY = `#!/usr/bin/env python3
"""
create-checkpoint.py — ONXZA Checkpoint Creator (stub)
Generated by onxza init. Replace with full version from onxza repository.

Usage: python3 create-checkpoint.py <event-slug>
Prints: checkpoint created: <checkpoint-id>

Imagined by Aaron Gear. Created by Aaron Gear and Marcus Gear (AI Co-Creator).
Powered by DevGru US Inc. DBA DevGru Technology Products.
"""
import sys, os, json, shutil, hashlib
from datetime import datetime, timezone

OPENCLAW_DIR    = os.path.expanduser("~/.openclaw")
CHECKPOINTS_DIR = os.path.join(OPENCLAW_DIR, "checkpoints")
OPENCLAW_JSON   = os.path.join(OPENCLAW_DIR, "openclaw.json")

def main():
    slug = sys.argv[1] if len(sys.argv) > 1 else "manual"
    ts   = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    cid  = f"{ts}-{slug}"
    cdir = os.path.join(CHECKPOINTS_DIR, cid)
    os.makedirs(cdir, exist_ok=True)

    # Snapshot openclaw.json
    if os.path.exists(OPENCLAW_JSON):
        shutil.copy2(OPENCLAW_JSON, os.path.join(cdir, "openclaw.json"))

    # Write manifest
    manifest = {"id": cid, "slug": slug, "created": ts, "tool": "onxza-init-stub"}
    with open(os.path.join(cdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # README
    with open(os.path.join(cdir, "README.md"), "w") as f:
        f.write(f"# Checkpoint: {cid}\\n\\nSlug: {slug}\\nCreated: {ts}\\n")

    print(f"checkpoint created: {cid}")

if __name__ == "__main__":
    main()
`;

/**
 * log-audit-entry.py stub.
 */
const LOG_AUDIT_ENTRY_PY = `#!/usr/bin/env python3
"""
log-audit-entry.py — ONXZA Audit Trail Logger (stub)
Generated by onxza init. Replace with full version from onxza repository.

Usage: python3 log-audit-entry.py --agent <id> --action <text> --outcome <text> ...

Imagined by Aaron Gear. Created by Aaron Gear and Marcus Gear (AI Co-Creator).
Powered by DevGru US Inc. DBA DevGru Technology Products.
"""
import sys, os, argparse
from datetime import datetime, timezone

WORKSPACE  = os.path.expanduser("~/.openclaw/workspace")
AUDIT_LOG  = os.path.join(WORKSPACE, "logs", "audit", "audit-trail.md")

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--agent",    default="unknown")
    p.add_argument("--action",   default="unknown")
    p.add_argument("--outcome",  default="pending")
    p.add_argument("--confirmed-by", default="pending")
    p.add_argument("--reversible",   default="yes")
    p.add_argument("--checkpoint-id", default="none")
    args = p.parse_args()

    ts   = datetime.now(timezone.utc).isoformat()
    line = (f"| {ts} | {args.agent} | {args.action} | {args.outcome} | "
            f"{args.confirmed_by} | reversible={args.reversible} | "
            f"checkpoint={args.checkpoint_id} |\\n")

    os.makedirs(os.path.dirname(AUDIT_LOG), exist_ok=True)
    if not os.path.exists(AUDIT_LOG):
        header = "# ONXZA Audit Trail\\n\\n| Timestamp | Agent | Action | Outcome | Confirmed By | Reversible | Checkpoint |\\n|---|---|---|---|---|---|---|\\n"
        with open(AUDIT_LOG, "w") as f: f.write(header)
    with open(AUDIT_LOG, "a") as f: f.write(line)
    print(f"audit entry logged: {ts}")

if __name__ == "__main__":
    main()
`;

// ---------------------------------------------------------------------------
// Pre-commit hook script
// ---------------------------------------------------------------------------

const PRE_COMMIT_HOOK = `#!/bin/sh
# ONXZA pre-commit hook — TORI-QMD validation
# Generated by onxza init. Runs validate-tori-qmd.py on all staged .md files.
#
# Imagined by Aaron Gear. Created by Aaron Gear and Marcus Gear (AI Co-Creator).
# Powered by DevGru US Inc. DBA DevGru Technology Products.

SCRIPT="$HOME/.openclaw/workspace/scripts/validate-tori-qmd.py"
PASS=0
FAIL=0

# Get staged .md files
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep '\\.md$' || true)

if [ -z "$STAGED" ]; then
  exit 0
fi

for FILE in $STAGED; do
  if [ -f "$FILE" ]; then
    RESULT=$(python3 "$SCRIPT" "$FILE" 2>&1)
    if echo "$RESULT" | grep -q "^PASS:"; then
      PASS=$((PASS + 1))
    else
      echo "  TORI-QMD FAIL: $FILE"
      echo "$RESULT" | grep "→" | head -5
      FAIL=$((FAIL + 1))
    fi
  fi
done

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "  $FAIL file(s) failed TORI-QMD. Fix before committing."
  echo "  Run: python3 ~/.openclaw/workspace/scripts/validate-tori-qmd.py <file>"
  exit 1
fi

echo "  TORI-QMD: $PASS file(s) passed."
exit 0
`;

// ---------------------------------------------------------------------------
// Ticket template
// ---------------------------------------------------------------------------

const TICKET_TEMPLATE = `---
id: TICKET-[YYYYMMDD]-[sequence]
created_by: [agent-name]
created_at: [ISO 8601 datetime]
assigned_to: [agent-name or role]
project: [project-slug]
priority: [low | medium | high | critical]
type: [task | approval_request | escalation | credentials_needed | vision_update_request]
status: [open | in-progress | pending-approval | blocked | closed]
requires_aaron: [true | false]
related_vision: [path to vision.md or "system"]
---

## Summary
[One sentence — what this ticket is about]

## Context
[Background needed to act on this ticket]

## Requested Action
[Specific deliverable — not "look into X" but "produce Y that does Z"]

## Vision Alignment
[One sentence connecting this to the project vision]

## Dependencies
[List of tickets or tasks that must complete first]

## Acceptance Criteria
[How will we know this is done correctly?]

## Notes / Updates
[Append updates here chronologically — never overwrite]

## Completion Note
[Written when closed — what was done, where output lives]
`;

// ---------------------------------------------------------------------------
// Main init logic
// ---------------------------------------------------------------------------

/**
 * Resolve the ONXZA base directory (contains workspace/, checkpoints/, etc.)
 */
function resolveBaseDir(optDir) {
  if (optDir && optDir !== process.cwd()) return path.resolve(optDir);
  return path.join(os.homedir(), '.openclaw');
}

/**
 * Check if an ONXZA installation already exists at baseDir.
 */
function detectExisting(baseDir) {
  const workspace   = path.join(baseDir, 'workspace');
  const ocjson      = path.join(baseDir, 'openclaw.json');
  const hasWorkspace = fs.existsSync(workspace);
  const hasJson      = fs.existsSync(ocjson);
  return { exists: hasWorkspace || hasJson, hasWorkspace, hasJson };
}

/**
 * Write a file only if it does not already exist (idempotent).
 * Returns 'created' | 'skipped'
 */
function writeIfMissing(filePath, content) {
  if (fs.existsSync(filePath)) return 'skipped';
  fs.writeFileSync(filePath, content, 'utf8');
  return 'created';
}

/**
 * Run the full init flow.
 * @param {object} opts
 * @param {string} opts.baseDir    - Target base directory
 * @param {boolean} opts.dryRun
 * @param {boolean} opts.force     - Force re-init even if exists
 * @param {function} opts.log      - Progress logger (msg, status?)
 * @returns {object} result
 */
function runInit(opts) {
  const { baseDir, dryRun, force, log } = opts;
  const steps  = [];
  const errors = [];

  // ── Step 1: Detect existing installation ─────────────────────────────────
  const existing = detectExisting(baseDir);

  if (existing.exists && !force) {
    log('Existing ONXZA installation detected.');
    log(`  workspace: ${existing.hasWorkspace ? '✓' : '✗'}   openclaw.json: ${existing.hasJson ? '✓' : '✗'}`);
    log('Running in idempotent mode — skipping already-created items.');
    log('Use --force to overwrite.');
    log('');
  }

  // ── Step 2: Create directory structure ───────────────────────────────────
  log('Creating workspace directory structure...');
  const createdDirs   = [];
  const existingDirs  = [];

  for (const { dir, desc } of WORKSPACE_DIRS) {
    const full = path.join(baseDir, dir);
    if (dryRun) {
      log(`  [dry-run] would create: ${full}`);
      steps.push({ step: 'mkdir', path: full, status: 'dry_run' });
      continue;
    }
    if (!fs.existsSync(full)) {
      fs.mkdirSync(full, { recursive: true });
      log(`  ✓ ${dir}`);
      createdDirs.push(full);
      steps.push({ step: 'mkdir', path: full, status: 'created' });
    } else {
      existingDirs.push(full);
      steps.push({ step: 'mkdir', path: full, status: 'skipped' });
    }
  }
  if (!dryRun) log(`  ${createdDirs.length} created, ${existingDirs.length} already existed.`);
  log('');

  // ── Step 3: Write openclaw.json ───────────────────────────────────────────
  log('Writing openclaw.json scaffold...');
  const ocJsonPath = path.join(baseDir, 'openclaw.json');
  if (!dryRun) {
    const status = writeIfMissing(ocJsonPath, JSON.stringify(generateOpenclawJson(), null, 2) + '\n');
    log(`  ${status === 'created' ? '✓ created' : '— already exists (skipped)'}: openclaw.json`);
    steps.push({ step: 'openclaw.json', path: ocJsonPath, status });
  } else {
    log(`  [dry-run] would write: ${ocJsonPath}`);
  }
  log('');

  // ── Step 4: Write governance scripts ─────────────────────────────────────
  log('Writing governance scripts...');
  const scripts = [
    { name: 'validate-tori-qmd.py',  content: VALIDATE_TORI_QMD_PY },
    { name: 'create-checkpoint.py',   content: CREATE_CHECKPOINT_PY },
    { name: 'log-audit-entry.py',     content: LOG_AUDIT_ENTRY_PY },
  ];
  const scriptsDir = path.join(baseDir, 'workspace', 'scripts');

  for (const s of scripts) {
    const scriptPath = path.join(scriptsDir, s.name);
    if (!dryRun) {
      const status = writeIfMissing(scriptPath, s.content);
      if (status === 'created') {
        try { fs.chmodSync(scriptPath, 0o755); } catch {}
      }
      log(`  ${status === 'created' ? '✓ created' : '— exists (skipped)'}: scripts/${s.name}`);
      steps.push({ step: 'script', path: scriptPath, status });
    } else {
      log(`  [dry-run] would write: ${scriptPath}`);
    }
  }
  log('');

  // ── Step 4b: Write ticket template ───────────────────────────────────────
  const templatePath = path.join(baseDir, 'workspace', 'tickets', 'TICKET_TEMPLATE.md');
  if (!dryRun) {
    const status = writeIfMissing(templatePath, TICKET_TEMPLATE);
    log(`  ${status === 'created' ? '✓ created' : '— exists'}: tickets/TICKET_TEMPLATE.md`);
    steps.push({ step: 'ticket_template', path: templatePath, status });
  }
  log('');

  // ── Step 5: Initialize git with pre-commit hook ───────────────────────────
  log('Initializing git repository with TORI-QMD pre-commit hook...');
  const gitDir      = path.join(baseDir, 'workspace');
  const dotGitPath  = path.join(gitDir, '.git');
  const hookPath    = path.join(gitDir, '.git', 'hooks', 'pre-commit');

  if (!dryRun) {
    try {
      if (!fs.existsSync(dotGitPath)) {
        execSync('git init', { cwd: gitDir, stdio: 'pipe' });
        log('  ✓ git init');
        steps.push({ step: 'git_init', path: gitDir, status: 'created' });
      } else {
        log('  — git already initialized (skipped)');
        steps.push({ step: 'git_init', path: gitDir, status: 'skipped' });
      }

      // Write pre-commit hook
      const hooksDir = path.join(dotGitPath, 'hooks');
      fs.mkdirSync(hooksDir, { recursive: true });
      const hookStatus = writeIfMissing(hookPath, PRE_COMMIT_HOOK);
      if (hookStatus === 'created') {
        fs.chmodSync(hookPath, 0o755);
        log('  ✓ pre-commit hook installed (TORI-QMD)');
      } else {
        log('  — pre-commit hook already exists (skipped)');
      }
      steps.push({ step: 'git_hook', path: hookPath, status: hookStatus });
    } catch (err) {
      const msg = `git init failed: ${err.message}`;
      log(`  ⚠  ${msg}`);
      errors.push(msg);
      steps.push({ step: 'git_init', path: gitDir, status: 'error', error: err.message });
    }
  } else {
    log(`  [dry-run] would run: git init ${gitDir}`);
    log(`  [dry-run] would install: pre-commit hook`);
  }
  log('');

  // ── Step 6: Create first checkpoint ──────────────────────────────────────
  log('Creating initial checkpoint...');
  let checkpoint = null;
  const checkpointScript = path.join(baseDir, 'workspace', 'scripts', 'create-checkpoint.py');

  if (!dryRun) {
    if (fs.existsSync(checkpointScript)) {
      try {
        const out = execFileSync('python3', [checkpointScript, 'onxza-init'], {
          encoding: 'utf8', timeout: 10000,
        });
        const m = out.match(/checkpoint created:\s*(\S+)/i);
        checkpoint = m ? m[1] : out.trim();
        log(`  ✓ Checkpoint: ${checkpoint}`);
        steps.push({ step: 'checkpoint', id: checkpoint, status: 'created' });
      } catch (err) {
        const msg = `Checkpoint failed: ${err.message}`;
        log(`  ⚠  ${msg}`);
        errors.push(msg);
        steps.push({ step: 'checkpoint', status: 'error', error: err.message });
      }
    } else {
      log('  ⚠  Checkpoint script not found — skipped');
      steps.push({ step: 'checkpoint', status: 'skipped' });
    }
  } else {
    log('  [dry-run] would create initial checkpoint');
  }
  log('');

  return { baseDir, steps, errors, checkpoint, dryRun };
}

// ---------------------------------------------------------------------------
// Command definition
// ---------------------------------------------------------------------------

const initCmd = new Command('init')
  .description('Initialize a new ONXZA installation (workspace, openclaw.json, scripts, git hook, checkpoint)')
  .option('--dir <path>', 'Base directory for ONXZA installation (default: ~/.openclaw)')
  .option('--force', 'Overwrite existing files (default: idempotent — skip existing)')
  .option('--dry-run', 'Show what would be created without making any changes')
  .option('--no-git', 'Skip git initialization')
  .action((options, cmd) => {
    const jsonMode = isJsonMode(cmd);
    const baseDir  = resolveBaseDir(options.dir);

    const messages = [];
    function log(msg) {
      if (!jsonMode) process.stdout.write(msg + '\n');
      messages.push(msg);
    }

    if (!jsonMode) {
      console.log('');
      console.log(`  ONXZA v0.1.0 — init${options.dryRun ? ' (dry run)' : ''}`);
      console.log(`  Target: ${baseDir}`);
      console.log(`  ${'─'.repeat(54)}`);
      console.log('');
    }

    const result = runInit({
      baseDir,
      dryRun: !!options.dryRun,
      force:  !!options.force,
      noGit:  options.git === false,
      log,
    });

    const created  = result.steps.filter((s) => s.status === 'created').length;
    const skipped  = result.steps.filter((s) => s.status === 'skipped').length;
    const errCount = result.errors.length;

    if (jsonMode) {
      outputJson({
        status:     errCount > 0 ? 'partial' : 'ok',
        dryRun:     result.dryRun,
        baseDir:    result.baseDir,
        checkpoint: result.checkpoint,
        summary:    { created, skipped, errors: errCount },
        steps:      result.steps,
        errors:     result.errors,
      });
      return;
    }

    if (result.dryRun) {
      console.log('  Dry run complete. No changes made.');
      console.log(`  Would create: ${result.steps.filter((s) => s.status === 'dry_run').length} items`);
      console.log('');
      return;
    }

    if (errCount > 0) {
      console.log(`  ⚠  Completed with ${errCount} warning(s):`);
      result.errors.forEach((e) => console.log(`    - ${e}`));
      console.log('');
    } else {
      console.log(`  ✓ ONXZA initialized successfully.`);
    }

    console.log(`  ${created} item(s) created, ${skipped} already existed.`);
    if (result.checkpoint) console.log(`  Checkpoint: ${result.checkpoint}`);
    console.log('');
    console.log('  Next steps:');
    console.log('    onxza agent create [Company]_[Dept]_[Role]   # Create your first agent');
    console.log('    onxza company add <name>                      # Register your company');
    console.log('    onxza status                                  # View system health');
    console.log('');
  });

module.exports = initCmd;
